name: Test delete branch

on:
  delete:
  workflow_dispatch:

jobs:
  delete-deployment:
    name: Build and update index.html
    runs-on: ubuntu-latest
    steps:
      - name: Echo branch
        run: |
          set -x
          GIT_BRANCH=$(echo ${{ github.event.ref }} | sed -e "s#refs/heads/##g")
          echo "GIT_BRANCH=$GIT_BRANCH"
          ls "$GIT_BRANCH"
